<?php

class SkiptaNewsFeedOption
{
  const FETCH_WORLD_FEED_SETTING = 'FETCH_WORLD_FEED_SETTING';
  const CONFIGURE_SETTING_UPDATE = 'CONFIGURE_SETTING_UPDATE';
  const CONFIGURE_SETTING_INSERT = 'CONFIGURE_SETTING_INSERT';
  const POPULATE_FEED_DATA = 'POPULATE_FEED_DATA';
  const USERS_WHO_LIKED = 'USERS_WHO_LIKED';
  const USERS_WHO_DISLIKED = 'USERS_WHO_DISLIKED';
  const UPDATE_LIKE_POST = 'UPDATE_LIKE_POST';
  const UPDATE_DISLIKE_POST = 'UPDATE_DISLIKE_POST';
  const INSERT_POST_RATING = 'INSERT_POST_RATING';
  const POST_USER_RATING = 'POST_USER_RATING';
  const GET_SKIPTA_WORLD = 'GET_SKIPTA_WORLD';
  const WORLD_NEWS_DATA = 'WORLD_NEWS_DATA';
  const INSERT_NEWS_COMMENT = 'INSERT_NEWS_COMMENT';
  const FETCH_NEWS_COMMENT = 'FETCH_NEWS_COMMENT';
  const LATEST_FEEDS = 'LATEST_FEEDS';
  const NEWS_ITEMS_IN_FEED = 'NEWS_ITEMS_IN_FEED';
  const FEED_AGGREGATE_COUNT = 'FEED_AGGREGATE_COUNT';
  const UPDATE_FEED_DATA = 'UPDATE_FEED_DATA';
  const NEWS_FEED_URL = 'NEWS_FEED_URL';
  const POST_USER_RATING_COMMENT = 'POST_USER_RATING_COMMENT';
  const DELETE_OLD_FEED_DATA = 'DELETE_OLD_FEED_DATA';
  const GET_NEWS_IDENTIFIER = 'GET_NEWS_IDENTIFIER';
  const RESET_CURRENT_NEWS_ITEMS = 'RESET_CURRENT_NEWS_ITEMS';


}
