<?php

class SkiptaPostQueryOption
{
  const TOTAL_RECORDS = 'TOTAL_RECORDS';
  const FRIEND_POSTS_BY_PAGE = 'FRIEND_POSTS_BY_PAGE';
  const FRIEND_POST_COMMENTS = 'FRIEND_POST_COMMENTS';
  const FRIEND_POST_ATTACHMENTS = 'FRIEND_POST_ATTACHMENTS';


}
