<?php

class SkiptaPostRatingOption
{
  const USERS_WHO_LIKED = 'USERS_WHO_LIKED';
  const USERS_WHO_DISLIKED = 'USERS_WHO_DISLIKED';
  const UPDATE_LIKE_POST = 'UPDATE_LIKE_POST';
  const UPDATE_DISLIKE_POST = 'UPDATE_DISLIKE_POST';
  const INSERT_POST_RATING = 'INSERT_POST_RATING';
  const RATED_USERS_INFO = 'RATED_USERS_INFO';
  const POST_USER_RATING = 'POST_USER_RATING';


}
